name: gdutils
channels:
  - conda-forge
dependencies:
  - python=3.9
  # gdutils
  - erddapy
  - ipydatetime
  - ipywidgets
  - matplotlib
  - pandas
  - python-dateutil
  - requests
  - seaborn
  - urllib3
